langage: c
install:
        - sudo add-apt-repository --yes ppa:snaipewastaken/ppa
        - sudo apt-get update
        - sudo apt-get install -y criterion-dev

script:  make test && ./test_run --verbose
